sudo: required

language: ruby

services:
  - docker

install:
 - docker-compose up -d

script:
 - docker-compose run -e RAILS_ENV=test lemonade_stand_api_web rake db:create
 - docker-compose run -e RAILS_ENV=test lemonade_stand_api_web rake db:migrate
 - docker-compose run -e RAILS_ENV=test lemonade_stand_api_web rake test

