version: "2"

services:
  lemonade_stand_api_web:
    build: .
    ports:
      - "3000"
    links:
      - lemonade_stand_api_db
    networks:
      - "internal"
  lemonade_stand_api_db:
    image: library/mysql:latest
    ports:
      - "3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - "internal"
networks:
  internal:
    driver: "bridge"
