default: &default
  adapter: mysql2
  host: lemonade_stand_api_db

development:
  <<: *default
  database: lemonade_stand_api_development

test:
  <<: *default
  database: lemonade_stand_api_test

production:
  <<: *default
  database: lemonade_stand_api_production
